### ISSUE TITLE
Doesn't work properly - Windows 10 64bit, build 1903

### ISSUE THREAD

**Issue by init5-SF** [x0xr00t/win-server2022-UAC-Bypass#2]
Hello,

this doesn't work for some reason, I modified the ps1 script as needed but running the script pops up UAC asking for Connection Manager elevation.
[https://i.ibb.co/kXH98LC/img.png](url)

Anything troubleshooting steps?

**Comment by x0xr00t** [comment]
I will look in to it, 

TIll then, check these thigs. 

* Make sure the exec policy is set in ps for the new user (Bypass, unrestricted, or remote)
* Make sure the dll (sl0p.dll) is made... (else make it)
* Make sure the secutity is lowered to the default. (so no security like under security tab tamper, or one of the other thing, just disable them to test it. )

The uac bypass is in no means a security bypass rather a mechanism that helps in dept security... 
So the uac bypass is not a security mechanism bypass that when security set to high, is bypassing that. 

I will tomorrow or day after look in to the windows 10 if and why u stumble on this issue.
